"""app/paraphrase.py 의 계산된 동의어 맵·데이터 테이블을 C#로 생성(codegen).

_syn_map 결과(_PRED_MAP/_VERB_MAP/_NOUN_MAP)와 각종 리스트/셋을 진리 소스에서 그대로
뽑아 ParaphraseData.cs 로 방출한다. (set 중복 제거·sorted·중복키 덮어쓰기 semantics 보존)

사용: PYTHONPATH=<repo> python csharp/tools/gen_paraphrase_data_cs.py
"""
from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))

import app.paraphrase as P  # noqa: E402


def cs_str(s: str) -> str:
    out = ['"']
    for ch in s:
        if ch == "\\": out.append("\\\\")
        elif ch == '"': out.append('\\"')
        elif ch == "\n": out.append("\\n")
        else: out.append(ch)
    out.append('"')
    return "".join(out)


def cs_arr(items) -> str:
    return "{ " + ", ".join(cs_str(x) for x in items) + " }"


def emit_map(name, d) -> list[str]:
    lines = [f"    public static readonly Dictionary<string, string[]> {name} = new()", "    {"]
    for k, v in d.items():
        lines.append(f"        [{cs_str(k)}] = new[] {cs_arr(v)},")
    lines.append("    };")
    return lines


def emit_set(name, s) -> list[str]:
    return [f"    public static readonly HashSet<string> {name} = new() {cs_arr(sorted(s))};"]


def emit_list(name, lst) -> list[str]:
    return [f"    public static readonly string[] {name} = new[] {cs_arr(lst)};"]


def main() -> int:
    L = ["// <auto-generated> csharp/tools/gen_paraphrase_data_cs.py. 진리: app/paraphrase.py",
         "namespace Saenggibu;", "", "public static class ParaphraseData", "{"]
    L += emit_map("PredMap", P._PRED_MAP); L.append("")
    L += emit_map("VerbMap", P._VERB_MAP); L.append("")
    L += emit_map("NounMap", P._NOUN_MAP); L.append("")
    L += emit_map("Ec", P._EC); L.append("")
    L += emit_map("SubjectEval", P._SUBJECT_EVAL); L.append("")
    # EvalPredSwap: 순서 의존(돋보임/보임 접미사 우선순위) → 순서 보존 배열
    L.append("    public static readonly (string pat, string[] reps)[] EvalPredSwap =")
    L.append("    {")
    for k, v in P._EVAL_PRED_SWAP.items():
        L.append(f"        ({cs_str(k)}, new[] {cs_arr(v)}),")
    L.append("    };")
    L.append("")
    L += emit_list("Adverbs", P._ADVERBS); L.append("")
    L += emit_list("Idioms", P._IDIOMS); L.append("")
    L += emit_list("EvalClauses", P._EVAL_CLAUSES); L.append("")
    L += emit_list("EvalConnectors", P._EVAL_CONNECTORS); L.append("")
    L += emit_set("SafeConn", P._SAFE_CONN); L.append("")
    L += emit_set("EvalNouns", P._EVAL_NOUNS); L.append("")
    L += emit_set("EvalNounsSubject", P._EVAL_NOUNS_SUBJECT); L.append("")
    L += emit_set("GenericNouns", P._GENERIC_NOUNS); L.append("")
    L += emit_list("Meta", list(P._META)); L.append("")
    L += emit_list("DriftWords", list(P._DRIFT_WORDS))
    L.append("}")
    dest = REPO / "csharp" / "Core" / "ParaphraseData.cs"
    dest.write_text("\n".join(L) + "\n", encoding="utf-8")
    print("wrote", dest)
    print(f"PredMap={len(P._PRED_MAP)} VerbMap={len(P._VERB_MAP)} NounMap={len(P._NOUN_MAP)} "
          f"Adverbs={len(P._ADVERBS)} Idioms={len(P._IDIOMS)} EvalClauses={len(P._EVAL_CLAUSES)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
