"""app/prompts.py 의 COMMON_RULES·AREAS 를 C# 데이터 파일로 정확히 생성한다.

방대한 한국어 원문을 손으로 옮기면 exact-match 파리티가 깨지기 쉬우므로,
진리 소스(Python)에서 그대로 뽑아 C# 문자열 리터럴로 방출한다.

사용: PYTHONPATH=<repo> python csharp/tools/gen_prompts_cs.py
"""
from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))

from app.prompts import AREAS, COMMON_RULES  # noqa: E402


def cs(s: str) -> str:
    """파이썬 문자열 → C# 문자열 리터럴(따옴표 포함)."""
    out = ['"']
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def main() -> int:
    lines: list[str] = []
    lines.append("// <auto-generated> csharp/tools/gen_prompts_cs.py 로 생성됨. 직접 수정 금지.")
    lines.append("// 진리 소스: app/prompts.py (COMMON_RULES, AREAS)")
    lines.append("namespace Saenggibu;")
    lines.append("")
    lines.append("public static class PromptsData")
    lines.append("{")
    lines.append(f"    public const string CommonRules = {cs(COMMON_RULES)};")
    lines.append("")
    lines.append("    public static readonly List<AreaSpec> Areas = new()")
    lines.append("    {")
    for a in AREAS:
        cs_subj = "true" if a.subject_field else "false"
        cold = a.cold_start
        lines.append("        new AreaSpec")
        lines.append("        {")
        lines.append(f"            Key = {cs(a.key)},")
        lines.append(f"            Title = {cs(a.title)},")
        lines.append(f"            SubjectField = {cs_subj},")
        lines.append(f"            CharLimit = {a.char_limit},")
        lines.append(f"            InputHint = {cs(a.input_hint)},")
        lines.append(f"            SystemExtra = {cs(a.system_extra)},")
        lines.append(f"            ColdStart = ({cs(cold[0])}, {cs(cold[1])}, {cs(cold[2])}),")
        lines.append("        },")
    lines.append("    };")
    lines.append("}")
    lines.append("")

    dest = REPO / "csharp" / "Core" / "PromptsData.cs"
    dest.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {dest} ({len(AREAS)} areas)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
